import type { AppLanguage } from "@/src/context/settings-context";

const exactTitles: Record<AppLanguage, Record<string, string>> = {
  sk: {
    "adult-resuscitation": "Resuscitácia dospelých",
    "adult-resuscitation/index": "Resuscitácia dospelých",
    "adult-resuscitation/als/4h4t": "4H / 4T",
    "adult-resuscitation/als/rosc": "ROSC",
    "adult-resuscitation/bradycardia/alternative-medications":
      "Alternatívne lieky",
    "adult-resuscitation/bradycardia/altmeds": "Alternatívne lieky",
    "adult-resuscitation/bradycardia/cardiostimulationscreen":
      "Kardiostimulácia",
    about: "O aplikácii a zdroje",
    epals: "Resuscitácia dieťaťa",
    "epals/index": "Resuscitácia dieťaťa",
    "epals/pals/roscpals": "Poresuscitačná starostlivosť",
    "epals/pals/termination": "Ukončenie resuscitácie",
    special: "Špeciálne okolnosti",
    "special/index": "Špeciálne okolnosti",
    "special/anafylaxia/refractory": "Refraktérna anafylaxia",
    "special/anafylaxia/cardiac-arrest": "Anafylaxia - ZO",
    "special/kalium/intro": "Poruchy draslíka",
    "special/kalium/hyper/cardiac-arrest": "Hyperkaliémia - ZO",
    "special/hypertermia/regular/step6": "Hyponatriémia",
    "special/hypertermia/regular/step8": "Rehydratácia",
    "special/hypotermia/hope-score": "HOPE skóre",
    "special/hypotermia/lavina/step1": "Záchrana z lavíny",
    "special/hypotermia/lavina/avalife": "AvaLife",
    "special/embolia/PEresuscitacia/step1": "Pľúcna embólia - ZO",
    "special/koronarnatromboza/st-elevation":
      "Koronárna trombóza - STEMI",
    "special/koronarnatromboza/ongoing-cpr": "Koronárna trombóza - KPR",
  },
  en: {
    "adult-resuscitation": "Adult Resuscitation",
    "adult-resuscitation/index": "Adult Resuscitation",
    "adult-resuscitation/als/4h4t": "4H / 4T",
    "adult-resuscitation/als/rosc": "ROSC",
    "adult-resuscitation/bradycardia/alternative-medications":
      "Alternative medicines",
    "adult-resuscitation/bradycardia/altmeds": "Alternative medicines",
    "adult-resuscitation/bradycardia/cardiostimulationscreen":
      "Cardiac pacing",
    about: "About and sources",
    epals: "Paediatric Resuscitation",
    "epals/index": "Paediatric Resuscitation",
    "epals/pals/roscpals": "Post-resuscitation care",
    "epals/pals/termination": "Termination of resuscitation",
    special: "Special Circumstances",
    "special/index": "Special Circumstances",
    "special/anafylaxia/refractory": "Refractory anaphylaxis",
    "special/anafylaxia/cardiac-arrest": "Anaphylaxis - arrest",
    "special/kalium/intro": "Potassium disorders",
    "special/kalium/hyper/cardiac-arrest": "Hyperkalaemia - arrest",
    "special/hypertermia/regular/step6": "Hyponatraemia",
    "special/hypertermia/regular/step8": "Rehydration",
    "special/hypotermia/hope-score": "HOPE score",
    "special/hypotermia/lavina/step1": "Avalanche rescue",
    "special/hypotermia/lavina/avalife": "AvaLife",
    "special/embolia/PEresuscitacia/step1": "Pulmonary embolism - arrest",
    "special/koronarnatromboza/st-elevation":
      "Coronary thrombosis - STEMI",
    "special/koronarnatromboza/ongoing-cpr": "Coronary thrombosis - CPR",
  },
};

const prefixTitles: Record<AppLanguage, readonly [prefix: string, title: string][]> = {
  sk: [
    ["adult-resuscitation/als/", "Rozšírená resuscitácia"],
    ["adult-resuscitation/bls/", "Základná resuscitácia"],
    ["adult-resuscitation/tachycardia/", "Tachykardia"],
    ["adult-resuscitation/bradycardia/", "Bradykardia"],
    ["epals/pals/", "Rozšírená resuscitácia"],
    ["epals/pbls/", "Základná resuscitácia"],
    ["epals/fbao/", "FBAO"],
    ["newborn/", "Resuscitácia novorodencov"],
    ["special/anafylaxia/", "Anafylaxia"],
    ["special/kalium/hyper/", "Hyperkaliémia"],
    ["special/kalium/hypo/", "Hypokaliémia"],
    ["special/hypertermia/maligna/", "Malígna hypertermia"],
    ["special/hypertermia/toxic/", "Hypertermia spôsobená toxínmi"],
    ["special/hypertermia/", "Hypertermia"],
    ["special/hypotermia/regular/step1", "Hypotermia"],
    ["special/hypotermia/regular/", "Náhodná hypotermia"],
    ["special/hypotermia/", "Hypotermia"],
    ["special/embolia/", "Pľúcna embólia"],
    ["special/koronarnatromboza/", "Koronárna trombóza"],
    ["special/toxic/", "Toxické látky"],
    ["special/trauma/", "Trauma"],
    ["special/astma-chochp/", "Astma a CHOCHP"],
    ["special/hemodialyza/", "Hemodialýza"],
    ["special/obezita/", "Obezita"],
    ["special/pectus-excavatum/", "Pectus excavatum"],
    ["special/pregnet/", "Tehotenstvo"],
    ["special/katetrizacne-pracovisko/", "Katetrizačné pracovisko"],
    ["special/topenie/", "Topenie"],
    ["special/operacna-sala/", "Operačná sála"],
    ["special/lokalne-anestetika/", "Toxicita lokálnych anestetík"],
    ["special/kardiochirurgia/", "Po kardiochirurgii"],
    ["special/lvad/", "Pacient s LVAD"],
    ["special/sport/", "Šport"],
    ["special/zzs-transport/", "ZZS a transport"],
    ["special/pocas-letu/", "Počas letu"],
    ["special/mikrogravitacia/", "Mikrogravitácia"],
    ["special/vyletna-lod/", "Výletná loď"],
  ],
  en: [
    ["adult-resuscitation/als/", "Advanced life support"],
    ["adult-resuscitation/bls/", "Basic life support"],
    ["adult-resuscitation/tachycardia/", "Tachycardia"],
    ["adult-resuscitation/bradycardia/", "Bradycardia"],
    ["epals/pals/", "Paediatric advanced life support"],
    ["epals/pbls/", "Paediatric basic life support"],
    ["epals/fbao/", "FBAO"],
    ["newborn/", "Newborn resuscitation"],
    ["special/anafylaxia/", "Anaphylaxis"],
    ["special/kalium/hyper/", "Hyperkalaemia"],
    ["special/kalium/hypo/", "Hypokalaemia"],
    ["special/hypertermia/maligna/", "Malignant hyperthermia"],
    ["special/hypertermia/toxic/", "Toxin-induced hyperthermia"],
    ["special/hypertermia/", "Hyperthermia"],
    ["special/hypotermia/regular/step1", "Hypothermia"],
    ["special/hypotermia/regular/", "Accidental hypothermia"],
    ["special/hypotermia/", "Hypothermia"],
    ["special/embolia/", "Pulmonary embolism"],
    ["special/koronarnatromboza/", "Coronary thrombosis"],
    ["special/toxic/", "Toxic agents"],
    ["special/trauma/", "Trauma"],
    ["special/astma-chochp/", "Asthma and COPD"],
    ["special/hemodialyza/", "Haemodialysis"],
    ["special/obezita/", "Obesity"],
    ["special/pectus-excavatum/", "Pectus excavatum"],
    ["special/pregnet/", "Pregnancy"],
    ["special/katetrizacne-pracovisko/", "Catheterisation laboratory"],
    ["special/topenie/", "Drowning"],
    ["special/operacna-sala/", "Operating room"],
    ["special/lokalne-anestetika/", "Local anaesthetic toxicity"],
    ["special/kardiochirurgia/", "Post cardiac surgery"],
    ["special/lvad/", "Patient with LVAD"],
    ["special/sport/", "Sport"],
    ["special/zzs-transport/", "EMS and transport"],
    ["special/pocas-letu/", "In-flight"],
    ["special/mikrogravitacia/", "Microgravity"],
    ["special/vyletna-lod/", "Cruise ship"],
  ],
};

export function getAlgorithmScreenTitle(
  routeName: string,
  language: AppLanguage = "sk",
) {
  const algorithmRoute = routeName.replace(/^algorithms\//, "");
  const exactTitle = exactTitles[language][algorithmRoute];

  if (exactTitle) {
    return exactTitle;
  }

  return (
    prefixTitles[language].find(([prefix]) =>
      algorithmRoute.startsWith(prefix),
    )?.[1] ?? "ERC 2025"
  );
}
